# Generated by Django 4.0.3 on 2022-03-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beverage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='arrergy',
            new_name='allergy',
        ),
    ]
