# Generated by Django 4.0.3 on 2022-03-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Beverage', '0002_rename_arrergy_drink_allergy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='allergy',
        ),
        migrations.CreateModel(
            name='allergy_drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beverage.allergy')),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beverage.drink')),
            ],
            options={
                'db_table': 'product_allergydrink',
            },
        ),
    ]
